# Generated by Django 4.1.4 on 2023-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(max_length=200)),
                ('lugar_nacimiento', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=200)),
                ('cedula_identidad', models.CharField(max_length=200)),
                ('numero_beneficiario', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], default='Soltero/a', max_length=50)),
                ('nombre_conyuge', models.CharField(max_length=200)),
                ('direccion_laboral', models.CharField(max_length=200)),
                ('entidad_dependencia', models.CharField(max_length=200)),
                ('profesion_ocupacion', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('disposicion_legal_jubilacion', models.CharField(max_length=200)),
                ('resolucion_numero', models.CharField(max_length=200)),
                ('imagen_cedula_frente', models.ImageField(upload_to='files/cedulas')),
                ('imagen_cedula_atras', models.ImageField(upload_to='files/cedulas')),
            ],
        ),
    ]
