# Generated by Django 4.1.4 on 2023-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nacionalidad',
            field=models.CharField(choices=[('Paraguaya', 'Paraguaya')], default='Paraguaya', max_length=25),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=50),
        ),
    ]
