# Generated by Django 4.1.4 on 2023-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_formulario_nacionalidad_alter_formulario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
