# Generated by Django 4.1.4 on 2023-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_formulario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
